create table if not exists arquivo_loteria (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) not null,
  data_cadastro timestamp not null default now()
);

create table if not exists arquivo_loteria_detalhe (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arquivo_loteria_id bigint not null references arquivo_loteria(id) on delete cascade,

  concurso integer not null,
  data_sorteio date not null,

  bola1 smallint not null,
  bola2 smallint not null,
  bola3 smallint not null,
  bola4 smallint not null,
  bola5 smallint not null,
  bola6 smallint not null,
  bola7 smallint not null,
  bola8 smallint not null,
  bola9 smallint not null,
  bola10 smallint not null,
  bola11 smallint not null,
  bola12 smallint not null,
  bola13 smallint not null,
  bola14 smallint not null,
  bola15 smallint not null
);

create index if not exists idx_ald_arquivo on arquivo_loteria_detalhe(arquivo_loteria_id);
create index if not exists idx_ald_concurso on arquivo_loteria_detalhe(concurso);

create unique index if not exists uk_ald_arquivo_concurso
on arquivo_loteria_detalhe(arquivo_loteria_id, concurso);


create table if not exists jogo_favorito (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  bola1 smallint not null,
  bola2 smallint not null,
  bola3 smallint not null,
  bola4 smallint not null,
  bola5 smallint not null,
  bola6 smallint not null,
  bola7 smallint not null,
  bola8 smallint not null,
  bola9 smallint not null,
  bola10 smallint not null,
  bola11 smallint not null,
  bola12 smallint not null,
  bola13 smallint not null,
  bola14 smallint not null,
  bola15 smallint not null,

  jogo_sorteado boolean not null default false,
  total_numeros_sorteados integer not null default 0
);

create index if not exists idx_jogo_favorito_total
on jogo_favorito(total_numeros_sorteados);